name: MLOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # agar bisa dijalankan secara manual dari GitHub UI

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Sesuaikan versi Python kamu

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: make install

      - name: Show installed packages
        run: pip freeze


      - name: Format code
        run: make format

      - name: Train model
        run: make train

      - name: Evaluate model
        run: make eval

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: results/
